package codeword;

/**
 * Thrown when there is a problem with the codeword either entered by the user
 * or generated by the program.
 * 
 * @author Bryan Rainbow
 *
 */
public class InvalidCodewordException extends Exception
{
	/**
	 * Construct an InvalidCodewordException with the specified data
	 * 
	 * @param msg the message describing the error
	 */
	public InvalidCodewordException(final String msg)
	{
		super(msg);
	}
}
